# Generated by Django 3.0.3 on 2020-03-05 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0002_auto_20200304_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superhero',
            options={'ordering': ['active']},
        ),
        migrations.AlterField(
            model_name='superhero',
            name='id',
            field=models.UUIDField(default=uuid.UUID('066969d3-c54e-48f9-a041-607e82333003'), editable=False, primary_key=True, serialize=False),
        ),
    ]
