# Generated by Django 3.0.3 on 2020-03-05 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0003_auto_20200304_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4883d00-603c-4b65-9d52-2a9771ac1377'), editable=False, primary_key=True, serialize=False),
        ),
    ]
