# Generated by Django 3.0.3 on 2020-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0006_auto_20200305_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
