# Generated by Django 3.0.3 on 2020-03-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0008_auto_20200305_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superhero',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='superhero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
