# Generated by Django 3.0.3 on 2020-03-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0009_auto_20200306_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='squadName',
            new_name='squadname',
        ),
    ]
