# Generated by Django 3.0.3 on 2020-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0010_auto_20200308_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='squadname',
            field=models.CharField(max_length=100),
        ),
    ]
