# Generated by Django 3.0.3 on 2020-03-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0011_auto_20200309_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='squadname',
            new_name='squad_name',
        ),
    ]
